FROM node:18

RUN apt-get update && apt-get install -y chromium ca-certificates fonts-liberation \
    && ln -s /usr/bin/chromium /usr/bin/chromium-browser \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g nodemon

COPY . .

EXPOSE 3001

CMD ["sh", "-c", "npx chokidar-cli 'package.json' -i '**/package-lock.json' -c 'if [ ! -f /tmp/npm_running ]; then touch /tmp/npm_running && echo Detected dependency change; npm install --no-audit --no-fund && rm -f /tmp/npm_running; fi' & nodemon --legacy-watch --watch . --ext js,json,env server.js"]



