
name: Deploy coylejax-backend to live-Production on EC2

on:
  push:
    branches:
      - release/production-live
  workflow_dispatch:
  

jobs:
  deploy:
    runs-on: [self-hosted, coylejax]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy Backend
        run: |
          echo "Starting deployment on staging server..."
    
          # Sync from runner workspace → target folder
          rsync -av --delete \
            --exclude ".env" \
            --exclude "uploads/" \
            --exclude ".git" \
            --exclude ".github" \
            ./ /home/ubuntu/coylejax-backend/

          cd /home/ubuntu/coylejax-backend

          npm install

          sudo pm2 restart coylejax-production
          sudo pm2 save
          sudo pm2 ls



# name: Backend Production Deployment with Docker Container

# on:
#   push:
#     branches:
#       - release/production-live
#   workflow_dispatch: 

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Log in to GHCR
#         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#       - name: Set lowercase owner
#         run: echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

#       - name: Build Docker image
#         run: docker build -t ghcr.io/$OWNER/coylejax-prod-backend:latest .

#       - name: Push Docker image
#         run: docker push ghcr.io/$OWNER/coylejax-prod-backend:latest

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to EC2 via SSH
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             echo "Logging into GHCR..."

#             sudo docker login ghcr.io \
#               -u ${{ github.repository_owner }} \
#               -p ${{ secrets.GHCR_TOKEN }}

#             echo "Pulling latest image..."
#             sudo docker pull ghcr.io/4glaciers/coylejax-prod-backend:latest

#             echo "Stopping old container..."
#             sudo docker stop coylejax-prod-backend || true
#             sudo docker rm coylejax-prod-backend || true

#             echo "Running new container..."
#             sudo docker run -d \
#               --name coylejax-prod-backend \
#               -p 3002:3002 \
#               -v /home/ubuntu/coylejax-backend/uploads:/app/uploads \
#               --env-file /home/ubuntu/coylejax-backend/.env \
#               --restart always \
#               ghcr.io/${{ github.repository_owner }}/coylejax-prod-backend:latest

#             echo "Waiting for container to initialize..."
#             sleep 5

#             echo "Checking container status..."
#             if [ "$(sudo docker inspect -f '{{.State.Running}}' coylejax-prod-backend)" != "true" ]; then
#               echo "❌ Container failed to start"
#               sudo docker logs coylejax-prod-backend
#               exit 1
#             fi
            
#             echo "cleaning unused images"
#             sudo docker image prune -f 

#             echo "Deployment completed!"
             